title: Bowen Li
description: Postdoctoral Researcher in Applied Mathematics at Linköping University
url: "https://bowenyl.github.io"
baseurl: ""
profile_image: /assets/img/bowen-liu.jpeg

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
