# reference and template repository: "academicpages/academicpages.github.io", "tyleransom/tyleransom.github.io", and "wsshin/jemdoc_mathjax"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Bowen Li
keywords: Bowen Li, bowen, math, Mathematics, Applied Mathematics, Computational Mathematics, Economics, Physics
logo: /assets/img/bowen.jpg
description: PhD Student<br />Academy of Mathematics and Systems Science<br />Chinese Academy of Sciences
email: bowen@lsec.cc.ac.cn
scholar: https://scholar.google.com/citations?hl=en&user=_L8IhJEAAAAJ
orcid: https://orcid.org/0009-0008-7809-7267
contact: Institute of Computational Mathematics and Scientific/Engineering Computing,<br />Academy of Mathematics and Systems Science,<br />No.55, ZhongGuanCun East Road, Beijing, China, 100190

nav:
- name: Home
  link: /
- name: Research
  link: /pages/research.html
- name: Resources
  link: /pages/resources.html
